const defaultPath = '../../src/assets/images'

export const constants = {
    screens: {
        home: 'Home',
        forgotPassword: 'ForgotPassword',
        signUp: 'SignUp',
        login: 'Login',
        dashBoard: 'Dashboard',
        announcements: 'Announcements',
        leaderBoard: 'LeaderBoard',
        selectionDays: "SelectionDays",
        myPicks: "MyPicks",
        dayPick: 'DayPick',
        joinWhatsApp: 'JoinWhatsApp',
        prizes: 'Prizes',
        changePassword: 'ChangePassword',
        aboutUs: 'AboutUs',
        membership: 'MemberShip',
        notification:'Notification',
        buyMemberShip:"BuyMemberShip",
        privateGroupDetails:"PrivateGroupDetails"
    },
    colors: {
        darkGreen: '#1D7A48',
        white: '#FFFFFF',
        backGroundLight: '#E5F9BD',
        labelColor: '#636363',
        commonButtonColor: '#23587B',
        grey: '#636363',
        bottomTabLight: '#A1A5B7',
        darkBlue: '#23587B',
        black: '#000000',
        lightestBlue: '#F5F8FA',
        cardColor: '#F2F5FA',
    },
    icons: {
        logo: require(`${defaultPath}/tennisClubLogo.png`),
        downArrow: require(`${defaultPath}/downArrow.png`),
        tennisBall: require(`${defaultPath}/tennisBall.png`),
        eye: require(`${defaultPath}/eye.png`),
        hiddenEye: require(`${defaultPath}/hidden.png`),
        backArrow: require(`${defaultPath}/back.png`),
        home: require(`${defaultPath}/home.png`),
        selectionDays: require(`${defaultPath}/Vector.png`),
        rules: require(`${defaultPath}/rules.png`),
        account: require(`${defaultPath}/shape.png`),
        whatsApp: require(`${defaultPath}/whatsApp.png`),
        shapeBell: require(`${defaultPath}/shapeBell.png`),
        winnerCup: require(`${defaultPath}/winnerCup.png`),
        participant: require(`${defaultPath}/User.png`),
        search: require(`${defaultPath}/search.png`),
        filter: require(`${defaultPath}/filter.png`),
        profileImage: require(`${defaultPath}/profileImage.png`),
        mail: require(`${defaultPath}/mail.png`),
        call: require(`${defaultPath}/call.png`),
        rightArrow: require(`${defaultPath}/rightArrow.png`),
        cart: require(`${defaultPath}/cart.png`),
        groupProfile: require(`${defaultPath}/groupProfile.png`),
        calander: require(`${defaultPath}/Calander.png`),
        tennisMembership: require(`${defaultPath}/TenisMembership.png`),
        elizabeth: require(`${defaultPath}/elizabeth.png`),
        Rackets: require(`${defaultPath}/Rackets.png`),
        profileMembership: require(`${defaultPath}/ProfileMembership.png`),
        effilTower: require(`${defaultPath}/effilTower.png`),
        map: require(`${defaultPath}/map.png`),
        whiteBackArrow: require(`${defaultPath}/whiteBackArrow.png`),
    },
    fonts: {
        exo2Regular: 'Exo2-Regular',
        exo2Bold: 'Exo2-Bold',
        exo2Light: 'Exo2-Light',
        notoSansBold: 'NotoSans-Bold',
        notoSansRegular: 'NotoSans-Regular',
        notoSansLight: 'NotoSans-Light',
        nuntinoRegular: 'Nunito-Regular',
        nuntinoBold: 'Nunito-Bold',
        nuntinoLight: 'Nunito-Light',
    }
} 